### ISSUE TITLE
Tour table, vertical scroll on iPad sticks, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/JaMmusic#135]
https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by JoshuaVSherman** [comment]
@Unesdala so you are saying that this has already been fixed now?
please in the future, make a new branch for each issue and tag it in the merge request so that I can keep track better, thanks

**Comment by Unesdala** [comment]
Yeah, it should be fixed now.

And alrighty, can do ^^

**Comment by JoshuaVSherman** [comment]
@chemmom2 please test this with your ipad, thank you

**Comment by JoshuaVSherman** [comment]
@Unesdala this is still not fixed, please fix this next, thank you!

**Comment by JoshuaVSherman** [comment]
@JoshuaVSherman find the ipad so I can test this
